apiVersion: v1
kind: Service
metadata:
  name: logiq
  namespace: trench-prod
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
spec:
  selector:
    app: logiq # Targets pods with the label app: logiq
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer # Changed from ClusterIP to LoadBalancer
